/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * AuraHire API
 * Backend API for AuraHire — Explainable + Fair AI-Powered Recruitment
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { fetcher } from "./fetcher.ts";
/**
 * @nullable
 */
export type CandidateSubprofileDtoHeadline = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type CandidateSubprofileDtoSummary = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type CandidateSubprofileDtoLocationCity = {
  [key: string]: unknown;
} | null;

/**
 * @nullable
 */
export type CandidateSubprofileDtoLocationCountry = {
  [key: string]: unknown;
} | null;

export interface CandidateSubprofileDto {
  /** @nullable */
  headline: CandidateSubprofileDtoHeadline;
  /** @nullable */
  summary: CandidateSubprofileDtoSummary;
  /** @nullable */
  locationCity: CandidateSubprofileDtoLocationCity;
  /** @nullable */
  locationCountry: CandidateSubprofileDtoLocationCountry;
  profileCompleted: boolean;
}

/**
 * @nullable
 */
export type RecruiterSubprofileDtoJobTitle = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type RecruiterSubprofileDtoDepartment = {
  [key: string]: unknown;
} | null;

export interface RecruiterSubprofileDto {
  companyId: string;
  /** @nullable */
  jobTitle: RecruiterSubprofileDtoJobTitle;
  /** @nullable */
  department: RecruiterSubprofileDtoDepartment;
  profileCompleted: boolean;
}

/**
 * @nullable
 */
export type CompanySummaryDtoIndustry = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type CompanySummaryDtoSize = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type CompanySummaryDtoWebsite = { [key: string]: unknown } | null;

export interface CompanySummaryDto {
  id: string;
  name: string;
  /** @nullable */
  industry: CompanySummaryDtoIndustry;
  /** @nullable */
  size: CompanySummaryDtoSize;
  /** @nullable */
  website: CompanySummaryDtoWebsite;
}

export type ProfileResponseDtoRole =
  (typeof ProfileResponseDtoRole)[keyof typeof ProfileResponseDtoRole];

export const ProfileResponseDtoRole = {
  candidate: "candidate",
  recruiter: "recruiter",
  admin: "admin",
} as const;

export type ProfileResponseDtoStatus =
  (typeof ProfileResponseDtoStatus)[keyof typeof ProfileResponseDtoStatus];

export const ProfileResponseDtoStatus = {
  active: "active",
  suspended: "suspended",
  deleted: "deleted",
} as const;

/**
 * @nullable
 */
export type ProfileResponseDtoPhone = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type ProfileResponseDtoAvatarUrl = { [key: string]: unknown } | null;

export interface ProfileResponseDto {
  id: string;
  email: string;
  fullName: string;
  role: ProfileResponseDtoRole;
  status: ProfileResponseDtoStatus;
  /** @nullable */
  phone: ProfileResponseDtoPhone;
  /** @nullable */
  avatarUrl: ProfileResponseDtoAvatarUrl;
  profileCompleted: boolean;
  candidateProfile: CandidateSubprofileDto | null;
  recruiterProfile: RecruiterSubprofileDto | null;
  company: CompanySummaryDto | null;
}

export interface ProfileResponseEnvelopeDto {
  data: ProfileResponseDto;
}

export interface InitCandidateProfileDto {
  /**
   * @minLength 2
   * @maxLength 100
   */
  fullName: string;
  /**
   * @minLength 7
   * @maxLength 20
   * @pattern ^[\d\s+()-]+$
   */
  phone: string;
}

export interface InitRecruiterProfileDto {
  /**
   * @minLength 2
   * @maxLength 100
   */
  fullName: string;
  /**
   * @minLength 7
   * @maxLength 20
   * @pattern ^[\d\s+()-]+$
   */
  phone: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  companyName: string;
}

/**
 * @summary Get the current user's profile + role-specific subprofile
 */
export type profilesControllerGetMeV1Response200 = {
  data: ProfileResponseEnvelopeDto;
  status: 200;
};

export type profilesControllerGetMeV1Response401 = {
  data: void;
  status: 401;
};

export type profilesControllerGetMeV1Response404 = {
  data: void;
  status: 404;
};

export type profilesControllerGetMeV1ResponseSuccess =
  profilesControllerGetMeV1Response200 & {
    headers: Headers;
  };
export type profilesControllerGetMeV1ResponseError = (
  | profilesControllerGetMeV1Response401
  | profilesControllerGetMeV1Response404
) & {
  headers: Headers;
};

export type profilesControllerGetMeV1Response =
  | profilesControllerGetMeV1ResponseSuccess
  | profilesControllerGetMeV1ResponseError;

export const getProfilesControllerGetMeV1Url = () => {
  return `/api/v1/profiles/me`;
};

export const profilesControllerGetMeV1 = async (
  options?: RequestInit,
): Promise<profilesControllerGetMeV1Response> => {
  return fetcher<profilesControllerGetMeV1Response>(
    getProfilesControllerGetMeV1Url(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getProfilesControllerGetMeV1QueryKey = () => {
  return [`/api/v1/profiles/me`] as const;
};

export const getProfilesControllerGetMeV1QueryOptions = <
  TData = Awaited<ReturnType<typeof profilesControllerGetMeV1>>,
  TError = void,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof profilesControllerGetMeV1>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getProfilesControllerGetMeV1QueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof profilesControllerGetMeV1>>
  > = ({ signal }) => profilesControllerGetMeV1({ signal });

  return {
    queryKey,
    queryFn,
    staleTime: 300000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof profilesControllerGetMeV1>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ProfilesControllerGetMeV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof profilesControllerGetMeV1>>
>;
export type ProfilesControllerGetMeV1QueryError = void;

/**
 * @summary Get the current user's profile + role-specific subprofile
 */

export function useProfilesControllerGetMeV1<
  TData = Awaited<ReturnType<typeof profilesControllerGetMeV1>>,
  TError = void,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof profilesControllerGetMeV1>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getProfilesControllerGetMeV1QueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Service health check
 */
export type healthControllerCheckResponse200 = {
  data: void;
  status: 200;
};

export type healthControllerCheckResponseSuccess =
  healthControllerCheckResponse200 & {
    headers: Headers;
  };
export type healthControllerCheckResponse =
  healthControllerCheckResponseSuccess;

export const getHealthControllerCheckUrl = () => {
  return `/api/health`;
};

export const healthControllerCheck = async (
  options?: RequestInit,
): Promise<healthControllerCheckResponse> => {
  return fetcher<healthControllerCheckResponse>(getHealthControllerCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthControllerCheckQueryKey = () => {
  return [`/api/health`] as const;
};

export const getHealthControllerCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthControllerCheck>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthControllerCheck>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthControllerCheckQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof healthControllerCheck>>
  > = ({ signal }) => healthControllerCheck({ signal });

  return {
    queryKey,
    queryFn,
    staleTime: 300000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof healthControllerCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthControllerCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthControllerCheck>>
>;
export type HealthControllerCheckQueryError = unknown;

/**
 * @summary Service health check
 */

export function useHealthControllerCheck<
  TData = Awaited<ReturnType<typeof healthControllerCheck>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthControllerCheck>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthControllerCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Frontend calls this AFTER supabase.auth.signUp() succeeds. The JWT identifies the new user; this endpoint creates profiles + candidate_profiles rows.
 * @summary Initialize a candidate profile after Supabase signUp
 */
export type authControllerRegisterCandidateV1Response201 = {
  data: ProfileResponseEnvelopeDto;
  status: 201;
};

export type authControllerRegisterCandidateV1Response401 = {
  data: void;
  status: 401;
};

export type authControllerRegisterCandidateV1Response409 = {
  data: void;
  status: 409;
};

export type authControllerRegisterCandidateV1ResponseSuccess =
  authControllerRegisterCandidateV1Response201 & {
    headers: Headers;
  };
export type authControllerRegisterCandidateV1ResponseError = (
  | authControllerRegisterCandidateV1Response401
  | authControllerRegisterCandidateV1Response409
) & {
  headers: Headers;
};

export type authControllerRegisterCandidateV1Response =
  | authControllerRegisterCandidateV1ResponseSuccess
  | authControllerRegisterCandidateV1ResponseError;

export const getAuthControllerRegisterCandidateV1Url = () => {
  return `/api/v1/auth/register-candidate`;
};

export const authControllerRegisterCandidateV1 = async (
  initCandidateProfileDto: InitCandidateProfileDto,
  options?: RequestInit,
): Promise<authControllerRegisterCandidateV1Response> => {
  return fetcher<authControllerRegisterCandidateV1Response>(
    getAuthControllerRegisterCandidateV1Url(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(initCandidateProfileDto),
    },
  );
};

export const getAuthControllerRegisterCandidateV1MutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerRegisterCandidateV1>>,
    TError,
    { data: InitCandidateProfileDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerRegisterCandidateV1>>,
  TError,
  { data: InitCandidateProfileDto },
  TContext
> => {
  const mutationKey = ["authControllerRegisterCandidateV1"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerRegisterCandidateV1>>,
    { data: InitCandidateProfileDto }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerRegisterCandidateV1(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerRegisterCandidateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerRegisterCandidateV1>>
>;
export type AuthControllerRegisterCandidateV1MutationBody =
  InitCandidateProfileDto;
export type AuthControllerRegisterCandidateV1MutationError = void;

/**
 * @summary Initialize a candidate profile after Supabase signUp
 */
export const useAuthControllerRegisterCandidateV1 = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerRegisterCandidateV1>>,
    TError,
    { data: InitCandidateProfileDto },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof authControllerRegisterCandidateV1>>,
  TError,
  { data: InitCandidateProfileDto },
  TContext
> => {
  return useMutation(
    getAuthControllerRegisterCandidateV1MutationOptions(options),
  );
};

/**
 * Frontend calls this AFTER supabase.auth.signUp() succeeds. Creates profiles + recruiter_profiles + companies rows in a single transaction.
 * @summary Initialize a recruiter profile + company after Supabase signUp
 */
export type authControllerRegisterRecruiterV1Response201 = {
  data: ProfileResponseEnvelopeDto;
  status: 201;
};

export type authControllerRegisterRecruiterV1Response401 = {
  data: void;
  status: 401;
};

export type authControllerRegisterRecruiterV1Response409 = {
  data: void;
  status: 409;
};

export type authControllerRegisterRecruiterV1ResponseSuccess =
  authControllerRegisterRecruiterV1Response201 & {
    headers: Headers;
  };
export type authControllerRegisterRecruiterV1ResponseError = (
  | authControllerRegisterRecruiterV1Response401
  | authControllerRegisterRecruiterV1Response409
) & {
  headers: Headers;
};

export type authControllerRegisterRecruiterV1Response =
  | authControllerRegisterRecruiterV1ResponseSuccess
  | authControllerRegisterRecruiterV1ResponseError;

export const getAuthControllerRegisterRecruiterV1Url = () => {
  return `/api/v1/auth/register-recruiter`;
};

export const authControllerRegisterRecruiterV1 = async (
  initRecruiterProfileDto: InitRecruiterProfileDto,
  options?: RequestInit,
): Promise<authControllerRegisterRecruiterV1Response> => {
  return fetcher<authControllerRegisterRecruiterV1Response>(
    getAuthControllerRegisterRecruiterV1Url(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(initRecruiterProfileDto),
    },
  );
};

export const getAuthControllerRegisterRecruiterV1MutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerRegisterRecruiterV1>>,
    TError,
    { data: InitRecruiterProfileDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerRegisterRecruiterV1>>,
  TError,
  { data: InitRecruiterProfileDto },
  TContext
> => {
  const mutationKey = ["authControllerRegisterRecruiterV1"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerRegisterRecruiterV1>>,
    { data: InitRecruiterProfileDto }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerRegisterRecruiterV1(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerRegisterRecruiterV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerRegisterRecruiterV1>>
>;
export type AuthControllerRegisterRecruiterV1MutationBody =
  InitRecruiterProfileDto;
export type AuthControllerRegisterRecruiterV1MutationError = void;

/**
 * @summary Initialize a recruiter profile + company after Supabase signUp
 */
export const useAuthControllerRegisterRecruiterV1 = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerRegisterRecruiterV1>>,
    TError,
    { data: InitRecruiterProfileDto },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof authControllerRegisterRecruiterV1>>,
  TError,
  { data: InitRecruiterProfileDto },
  TContext
> => {
  return useMutation(
    getAuthControllerRegisterRecruiterV1MutationOptions(options),
  );
};
