/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * AuraHire API
 * Backend API for AuraHire — Explainable + Fair AI-Powered Recruitment
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { fetcher } from "./fetcher";
/**
 * @nullable
 */
export type CandidateSubprofileDtoHeadline = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type CandidateSubprofileDtoSummary = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type CandidateSubprofileDtoLocationCity = {
  [key: string]: unknown;
} | null;

/**
 * @nullable
 */
export type CandidateSubprofileDtoLocationCountry = {
  [key: string]: unknown;
} | null;

export interface CandidateSubprofileDto {
  /** @nullable */
  headline: CandidateSubprofileDtoHeadline;
  /** @nullable */
  summary: CandidateSubprofileDtoSummary;
  /** @nullable */
  locationCity: CandidateSubprofileDtoLocationCity;
  /** @nullable */
  locationCountry: CandidateSubprofileDtoLocationCountry;
  profileCompleted: boolean;
}

/**
 * @nullable
 */
export type RecruiterSubprofileDtoJobTitle = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type RecruiterSubprofileDtoDepartment = {
  [key: string]: unknown;
} | null;

export interface RecruiterSubprofileDto {
  companyId: string;
  /** @nullable */
  jobTitle: RecruiterSubprofileDtoJobTitle;
  /** @nullable */
  department: RecruiterSubprofileDtoDepartment;
  profileCompleted: boolean;
}

/**
 * @nullable
 */
export type CompanySummaryDtoIndustry = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type CompanySummaryDtoSize = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type CompanySummaryDtoWebsite = { [key: string]: unknown } | null;

export interface CompanySummaryDto {
  id: string;
  name: string;
  /** @nullable */
  industry: CompanySummaryDtoIndustry;
  /** @nullable */
  size: CompanySummaryDtoSize;
  /** @nullable */
  website: CompanySummaryDtoWebsite;
}

export type ProfileResponseDtoRole =
  (typeof ProfileResponseDtoRole)[keyof typeof ProfileResponseDtoRole];

export const ProfileResponseDtoRole = {
  candidate: "candidate",
  recruiter: "recruiter",
  admin: "admin",
} as const;

export type ProfileResponseDtoStatus =
  (typeof ProfileResponseDtoStatus)[keyof typeof ProfileResponseDtoStatus];

export const ProfileResponseDtoStatus = {
  active: "active",
  suspended: "suspended",
  deleted: "deleted",
} as const;

/**
 * @nullable
 */
export type ProfileResponseDtoPhone = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type ProfileResponseDtoAvatarUrl = { [key: string]: unknown } | null;

export interface ProfileResponseDto {
  id: string;
  email: string;
  fullName: string;
  role: ProfileResponseDtoRole;
  status: ProfileResponseDtoStatus;
  /** @nullable */
  phone: ProfileResponseDtoPhone;
  /** @nullable */
  avatarUrl: ProfileResponseDtoAvatarUrl;
  profileCompleted: boolean;
  candidateProfile: CandidateSubprofileDto | null;
  recruiterProfile: RecruiterSubprofileDto | null;
  company: CompanySummaryDto | null;
}

export interface ProfileResponseEnvelopeDto {
  data: ProfileResponseDto;
}

/**
 * @nullable
 */
export type RecruiterCompanyDtoIndustry = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type RecruiterCompanyDtoSize = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type RecruiterCompanyDtoWebsite = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type RecruiterCompanyDtoHeadquartersLocation = {
  [key: string]: unknown;
} | null;

/**
 * @nullable
 */
export type RecruiterCompanyDtoDescription = { [key: string]: unknown } | null;

export interface RecruiterCompanyDto {
  id: string;
  name: string;
  /** @nullable */
  industry: RecruiterCompanyDtoIndustry;
  /** @nullable */
  size: RecruiterCompanyDtoSize;
  /** @nullable */
  website: RecruiterCompanyDtoWebsite;
  /** @nullable */
  headquartersLocation: RecruiterCompanyDtoHeadquartersLocation;
  /** @nullable */
  description: RecruiterCompanyDtoDescription;
}

/**
 * @nullable
 */
export type RecruiterProfileMeDtoPhone = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type RecruiterProfileMeDtoJobTitle = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type RecruiterProfileMeDtoDepartment = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type RecruiterProfileMeDtoHiringVolumePerQuarter = {
  [key: string]: unknown;
} | null;

export interface RecruiterProfileMeDto {
  id: string;
  email: string;
  fullName: string;
  /** @nullable */
  phone: RecruiterProfileMeDtoPhone;
  /** @nullable */
  jobTitle: RecruiterProfileMeDtoJobTitle;
  /** @nullable */
  department: RecruiterProfileMeDtoDepartment;
  rolesHiringFor: string[];
  /** @nullable */
  hiringVolumePerQuarter: RecruiterProfileMeDtoHiringVolumePerQuarter;
  profileCompleted: boolean;
  company: RecruiterCompanyDto;
}

export interface RecruiterProfileEnvelopeDto {
  data: RecruiterProfileMeDto;
}

export interface UpdateRecruiterAboutDto {
  /**
   * @minLength 2
   * @maxLength 100
   */
  fullName: string;
  /**
   * @minLength 7
   * @maxLength 20
   * @pattern ^[\d\s+()-]+$
   */
  phone: string;
  /**
   * @maxLength 150
   * @nullable
   */
  jobTitle?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  department?: string | null;
}

/**
 * @nullable
 */
export type UpdateRecruiterCompanyDtoSize =
  | (typeof UpdateRecruiterCompanyDtoSize)[keyof typeof UpdateRecruiterCompanyDtoSize]
  | null;

export const UpdateRecruiterCompanyDtoSize = {
  "1-10": "1-10",
  "11-50": "11-50",
  "51-200": "51-200",
  "201-500": "201-500",
  "501-1000": "501-1000",
  "1000+": "1000+",
} as const;

export interface UpdateRecruiterCompanyDto {
  /**
   * @minLength 1
   * @maxLength 200
   */
  companyName: string;
  /**
   * @maxLength 100
   * @nullable
   */
  industry?: string | null;
  /** @nullable */
  size?: UpdateRecruiterCompanyDtoSize;
  /** @nullable */
  website?: string | null;
  /** @nullable */
  headquartersLocation?: string | null;
  /**
   * @maxLength 2000
   * @nullable
   */
  description?: string | null;
}

/**
 * @nullable
 */
export type UpdateRecruiterFocusDtoHiringVolumePerQuarter =
  | (typeof UpdateRecruiterFocusDtoHiringVolumePerQuarter)[keyof typeof UpdateRecruiterFocusDtoHiringVolumePerQuarter]
  | null;

export const UpdateRecruiterFocusDtoHiringVolumePerQuarter = {
  "1-5": "1-5",
  "6-10": "6-10",
  "11-25": "11-25",
  "25+": "25+",
} as const;

export interface UpdateRecruiterFocusDto {
  rolesHiringFor?: string[];
  /** @nullable */
  hiringVolumePerQuarter?: UpdateRecruiterFocusDtoHiringVolumePerQuarter;
}

export interface InitCandidateProfileDto {
  /**
   * @minLength 2
   * @maxLength 100
   */
  fullName: string;
  /**
   * @minLength 7
   * @maxLength 20
   * @pattern ^[\d\s+()-]+$
   */
  phone: string;
}

export interface InitRecruiterProfileDto {
  /**
   * @minLength 2
   * @maxLength 100
   */
  fullName: string;
  /**
   * @minLength 7
   * @maxLength 20
   * @pattern ^[\d\s+()-]+$
   */
  phone: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  companyName: string;
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get the current user's profile + role-specific subprofile
 */
export type profilesControllerGetMeV1Response200 = {
  data: ProfileResponseEnvelopeDto;
  status: 200;
};

export type profilesControllerGetMeV1Response401 = {
  data: void;
  status: 401;
};

export type profilesControllerGetMeV1Response404 = {
  data: void;
  status: 404;
};

export type profilesControllerGetMeV1ResponseSuccess =
  profilesControllerGetMeV1Response200 & {
    headers: Headers;
  };
export type profilesControllerGetMeV1ResponseError = (
  | profilesControllerGetMeV1Response401
  | profilesControllerGetMeV1Response404
) & {
  headers: Headers;
};

export type profilesControllerGetMeV1Response =
  | profilesControllerGetMeV1ResponseSuccess
  | profilesControllerGetMeV1ResponseError;

export const getProfilesControllerGetMeV1Url = () => {
  return `/api/v1/profiles/me`;
};

export const profilesControllerGetMeV1 = async (
  options?: RequestInit,
): Promise<profilesControllerGetMeV1Response> => {
  return fetcher<profilesControllerGetMeV1Response>(
    getProfilesControllerGetMeV1Url(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getProfilesControllerGetMeV1QueryKey = () => {
  return [`/api/v1/profiles/me`] as const;
};

export const getProfilesControllerGetMeV1QueryOptions = <
  TData = Awaited<ReturnType<typeof profilesControllerGetMeV1>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof profilesControllerGetMeV1>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof fetcher>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getProfilesControllerGetMeV1QueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof profilesControllerGetMeV1>>
  > = ({ signal }) => profilesControllerGetMeV1({ signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    staleTime: 300000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof profilesControllerGetMeV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfilesControllerGetMeV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof profilesControllerGetMeV1>>
>;
export type ProfilesControllerGetMeV1QueryError = void;

export function useProfilesControllerGetMeV1<
  TData = Awaited<ReturnType<typeof profilesControllerGetMeV1>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profilesControllerGetMeV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof profilesControllerGetMeV1>>,
          TError,
          Awaited<ReturnType<typeof profilesControllerGetMeV1>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProfilesControllerGetMeV1<
  TData = Awaited<ReturnType<typeof profilesControllerGetMeV1>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profilesControllerGetMeV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof profilesControllerGetMeV1>>,
          TError,
          Awaited<ReturnType<typeof profilesControllerGetMeV1>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProfilesControllerGetMeV1<
  TData = Awaited<ReturnType<typeof profilesControllerGetMeV1>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profilesControllerGetMeV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get the current user's profile + role-specific subprofile
 */

export function useProfilesControllerGetMeV1<
  TData = Awaited<ReturnType<typeof profilesControllerGetMeV1>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profilesControllerGetMeV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getProfilesControllerGetMeV1QueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get the authenticated recruiter's full profile + company
 */
export type recruiterProfilesControllerGetMeV1Response200 = {
  data: RecruiterProfileEnvelopeDto;
  status: 200;
};

export type recruiterProfilesControllerGetMeV1Response403 = {
  data: void;
  status: 403;
};

export type recruiterProfilesControllerGetMeV1ResponseSuccess =
  recruiterProfilesControllerGetMeV1Response200 & {
    headers: Headers;
  };
export type recruiterProfilesControllerGetMeV1ResponseError =
  recruiterProfilesControllerGetMeV1Response403 & {
    headers: Headers;
  };

export type recruiterProfilesControllerGetMeV1Response =
  | recruiterProfilesControllerGetMeV1ResponseSuccess
  | recruiterProfilesControllerGetMeV1ResponseError;

export const getRecruiterProfilesControllerGetMeV1Url = () => {
  return `/api/v1/recruiter-profiles/me`;
};

export const recruiterProfilesControllerGetMeV1 = async (
  options?: RequestInit,
): Promise<recruiterProfilesControllerGetMeV1Response> => {
  return fetcher<recruiterProfilesControllerGetMeV1Response>(
    getRecruiterProfilesControllerGetMeV1Url(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getRecruiterProfilesControllerGetMeV1QueryKey = () => {
  return [`/api/v1/recruiter-profiles/me`] as const;
};

export const getRecruiterProfilesControllerGetMeV1QueryOptions = <
  TData = Awaited<ReturnType<typeof recruiterProfilesControllerGetMeV1>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof recruiterProfilesControllerGetMeV1>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof fetcher>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getRecruiterProfilesControllerGetMeV1QueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof recruiterProfilesControllerGetMeV1>>
  > = ({ signal }) =>
    recruiterProfilesControllerGetMeV1({ signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    staleTime: 300000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof recruiterProfilesControllerGetMeV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RecruiterProfilesControllerGetMeV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof recruiterProfilesControllerGetMeV1>>
>;
export type RecruiterProfilesControllerGetMeV1QueryError = void;

export function useRecruiterProfilesControllerGetMeV1<
  TData = Awaited<ReturnType<typeof recruiterProfilesControllerGetMeV1>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof recruiterProfilesControllerGetMeV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof recruiterProfilesControllerGetMeV1>>,
          TError,
          Awaited<ReturnType<typeof recruiterProfilesControllerGetMeV1>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useRecruiterProfilesControllerGetMeV1<
  TData = Awaited<ReturnType<typeof recruiterProfilesControllerGetMeV1>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof recruiterProfilesControllerGetMeV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof recruiterProfilesControllerGetMeV1>>,
          TError,
          Awaited<ReturnType<typeof recruiterProfilesControllerGetMeV1>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useRecruiterProfilesControllerGetMeV1<
  TData = Awaited<ReturnType<typeof recruiterProfilesControllerGetMeV1>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof recruiterProfilesControllerGetMeV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get the authenticated recruiter's full profile + company
 */

export function useRecruiterProfilesControllerGetMeV1<
  TData = Awaited<ReturnType<typeof recruiterProfilesControllerGetMeV1>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof recruiterProfilesControllerGetMeV1>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getRecruiterProfilesControllerGetMeV1QueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Onboarding step 1: about you
 */
export type recruiterProfilesControllerUpdateAboutV1Response200 = {
  data: RecruiterProfileEnvelopeDto;
  status: 200;
};

export type recruiterProfilesControllerUpdateAboutV1ResponseSuccess =
  recruiterProfilesControllerUpdateAboutV1Response200 & {
    headers: Headers;
  };
export type recruiterProfilesControllerUpdateAboutV1Response =
  recruiterProfilesControllerUpdateAboutV1ResponseSuccess;

export const getRecruiterProfilesControllerUpdateAboutV1Url = () => {
  return `/api/v1/recruiter-profiles/about`;
};

export const recruiterProfilesControllerUpdateAboutV1 = async (
  updateRecruiterAboutDto: UpdateRecruiterAboutDto,
  options?: RequestInit,
): Promise<recruiterProfilesControllerUpdateAboutV1Response> => {
  return fetcher<recruiterProfilesControllerUpdateAboutV1Response>(
    getRecruiterProfilesControllerUpdateAboutV1Url(),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateRecruiterAboutDto),
    },
  );
};

export const getRecruiterProfilesControllerUpdateAboutV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof recruiterProfilesControllerUpdateAboutV1>>,
    TError,
    { data: UpdateRecruiterAboutDto },
    TContext
  >;
  request?: SecondParameter<typeof fetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof recruiterProfilesControllerUpdateAboutV1>>,
  TError,
  { data: UpdateRecruiterAboutDto },
  TContext
> => {
  const mutationKey = ["recruiterProfilesControllerUpdateAboutV1"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof recruiterProfilesControllerUpdateAboutV1>>,
    { data: UpdateRecruiterAboutDto }
  > = (props) => {
    const { data } = props ?? {};

    return recruiterProfilesControllerUpdateAboutV1(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RecruiterProfilesControllerUpdateAboutV1MutationResult =
  NonNullable<
    Awaited<ReturnType<typeof recruiterProfilesControllerUpdateAboutV1>>
  >;
export type RecruiterProfilesControllerUpdateAboutV1MutationBody =
  UpdateRecruiterAboutDto;
export type RecruiterProfilesControllerUpdateAboutV1MutationError = unknown;

/**
 * @summary Onboarding step 1: about you
 */
export const useRecruiterProfilesControllerUpdateAboutV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof recruiterProfilesControllerUpdateAboutV1>>,
      TError,
      { data: UpdateRecruiterAboutDto },
      TContext
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof recruiterProfilesControllerUpdateAboutV1>>,
  TError,
  { data: UpdateRecruiterAboutDto },
  TContext
> => {
  return useMutation(
    getRecruiterProfilesControllerUpdateAboutV1MutationOptions(options),
    queryClient,
  );
};

/**
 * @summary Onboarding step 2: company details
 */
export type recruiterProfilesControllerUpdateCompanyV1Response200 = {
  data: RecruiterProfileEnvelopeDto;
  status: 200;
};

export type recruiterProfilesControllerUpdateCompanyV1ResponseSuccess =
  recruiterProfilesControllerUpdateCompanyV1Response200 & {
    headers: Headers;
  };
export type recruiterProfilesControllerUpdateCompanyV1Response =
  recruiterProfilesControllerUpdateCompanyV1ResponseSuccess;

export const getRecruiterProfilesControllerUpdateCompanyV1Url = () => {
  return `/api/v1/recruiter-profiles/company`;
};

export const recruiterProfilesControllerUpdateCompanyV1 = async (
  updateRecruiterCompanyDto: UpdateRecruiterCompanyDto,
  options?: RequestInit,
): Promise<recruiterProfilesControllerUpdateCompanyV1Response> => {
  return fetcher<recruiterProfilesControllerUpdateCompanyV1Response>(
    getRecruiterProfilesControllerUpdateCompanyV1Url(),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateRecruiterCompanyDto),
    },
  );
};

export const getRecruiterProfilesControllerUpdateCompanyV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof recruiterProfilesControllerUpdateCompanyV1>>,
    TError,
    { data: UpdateRecruiterCompanyDto },
    TContext
  >;
  request?: SecondParameter<typeof fetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof recruiterProfilesControllerUpdateCompanyV1>>,
  TError,
  { data: UpdateRecruiterCompanyDto },
  TContext
> => {
  const mutationKey = ["recruiterProfilesControllerUpdateCompanyV1"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof recruiterProfilesControllerUpdateCompanyV1>>,
    { data: UpdateRecruiterCompanyDto }
  > = (props) => {
    const { data } = props ?? {};

    return recruiterProfilesControllerUpdateCompanyV1(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RecruiterProfilesControllerUpdateCompanyV1MutationResult =
  NonNullable<
    Awaited<ReturnType<typeof recruiterProfilesControllerUpdateCompanyV1>>
  >;
export type RecruiterProfilesControllerUpdateCompanyV1MutationBody =
  UpdateRecruiterCompanyDto;
export type RecruiterProfilesControllerUpdateCompanyV1MutationError = unknown;

/**
 * @summary Onboarding step 2: company details
 */
export const useRecruiterProfilesControllerUpdateCompanyV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof recruiterProfilesControllerUpdateCompanyV1>>,
      TError,
      { data: UpdateRecruiterCompanyDto },
      TContext
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof recruiterProfilesControllerUpdateCompanyV1>>,
  TError,
  { data: UpdateRecruiterCompanyDto },
  TContext
> => {
  return useMutation(
    getRecruiterProfilesControllerUpdateCompanyV1MutationOptions(options),
    queryClient,
  );
};

/**
 * @summary Onboarding step 3 (final): hiring focus — flips profile_completed=true
 */
export type recruiterProfilesControllerUpdateFocusV1Response200 = {
  data: RecruiterProfileEnvelopeDto;
  status: 200;
};

export type recruiterProfilesControllerUpdateFocusV1ResponseSuccess =
  recruiterProfilesControllerUpdateFocusV1Response200 & {
    headers: Headers;
  };
export type recruiterProfilesControllerUpdateFocusV1Response =
  recruiterProfilesControllerUpdateFocusV1ResponseSuccess;

export const getRecruiterProfilesControllerUpdateFocusV1Url = () => {
  return `/api/v1/recruiter-profiles/focus`;
};

export const recruiterProfilesControllerUpdateFocusV1 = async (
  updateRecruiterFocusDto: UpdateRecruiterFocusDto,
  options?: RequestInit,
): Promise<recruiterProfilesControllerUpdateFocusV1Response> => {
  return fetcher<recruiterProfilesControllerUpdateFocusV1Response>(
    getRecruiterProfilesControllerUpdateFocusV1Url(),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateRecruiterFocusDto),
    },
  );
};

export const getRecruiterProfilesControllerUpdateFocusV1MutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof recruiterProfilesControllerUpdateFocusV1>>,
    TError,
    { data: UpdateRecruiterFocusDto },
    TContext
  >;
  request?: SecondParameter<typeof fetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof recruiterProfilesControllerUpdateFocusV1>>,
  TError,
  { data: UpdateRecruiterFocusDto },
  TContext
> => {
  const mutationKey = ["recruiterProfilesControllerUpdateFocusV1"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof recruiterProfilesControllerUpdateFocusV1>>,
    { data: UpdateRecruiterFocusDto }
  > = (props) => {
    const { data } = props ?? {};

    return recruiterProfilesControllerUpdateFocusV1(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RecruiterProfilesControllerUpdateFocusV1MutationResult =
  NonNullable<
    Awaited<ReturnType<typeof recruiterProfilesControllerUpdateFocusV1>>
  >;
export type RecruiterProfilesControllerUpdateFocusV1MutationBody =
  UpdateRecruiterFocusDto;
export type RecruiterProfilesControllerUpdateFocusV1MutationError = unknown;

/**
 * @summary Onboarding step 3 (final): hiring focus — flips profile_completed=true
 */
export const useRecruiterProfilesControllerUpdateFocusV1 = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof recruiterProfilesControllerUpdateFocusV1>>,
      TError,
      { data: UpdateRecruiterFocusDto },
      TContext
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof recruiterProfilesControllerUpdateFocusV1>>,
  TError,
  { data: UpdateRecruiterFocusDto },
  TContext
> => {
  return useMutation(
    getRecruiterProfilesControllerUpdateFocusV1MutationOptions(options),
    queryClient,
  );
};

/**
 * @summary Service health check
 */
export type healthControllerCheckResponse200 = {
  data: void;
  status: 200;
};

export type healthControllerCheckResponseSuccess =
  healthControllerCheckResponse200 & {
    headers: Headers;
  };
export type healthControllerCheckResponse =
  healthControllerCheckResponseSuccess;

export const getHealthControllerCheckUrl = () => {
  return `/api/health`;
};

export const healthControllerCheck = async (
  options?: RequestInit,
): Promise<healthControllerCheckResponse> => {
  return fetcher<healthControllerCheckResponse>(getHealthControllerCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthControllerCheckQueryKey = () => {
  return [`/api/health`] as const;
};

export const getHealthControllerCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthControllerCheck>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof healthControllerCheck>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof fetcher>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthControllerCheckQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof healthControllerCheck>>
  > = ({ signal }) => healthControllerCheck({ signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    staleTime: 300000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof healthControllerCheck>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type HealthControllerCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthControllerCheck>>
>;
export type HealthControllerCheckQueryError = unknown;

export function useHealthControllerCheck<
  TData = Awaited<ReturnType<typeof healthControllerCheck>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthControllerCheck>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthControllerCheck>>,
          TError,
          Awaited<ReturnType<typeof healthControllerCheck>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealthControllerCheck<
  TData = Awaited<ReturnType<typeof healthControllerCheck>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthControllerCheck>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthControllerCheck>>,
          TError,
          Awaited<ReturnType<typeof healthControllerCheck>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealthControllerCheck<
  TData = Awaited<ReturnType<typeof healthControllerCheck>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthControllerCheck>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Service health check
 */

export function useHealthControllerCheck<
  TData = Awaited<ReturnType<typeof healthControllerCheck>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthControllerCheck>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getHealthControllerCheckQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Frontend calls this AFTER supabase.auth.signUp() succeeds. The JWT identifies the new user; this endpoint creates profiles + candidate_profiles rows.
 * @summary Initialize a candidate profile after Supabase signUp
 */
export type authControllerRegisterCandidateV1Response201 = {
  data: ProfileResponseEnvelopeDto;
  status: 201;
};

export type authControllerRegisterCandidateV1Response401 = {
  data: void;
  status: 401;
};

export type authControllerRegisterCandidateV1Response409 = {
  data: void;
  status: 409;
};

export type authControllerRegisterCandidateV1ResponseSuccess =
  authControllerRegisterCandidateV1Response201 & {
    headers: Headers;
  };
export type authControllerRegisterCandidateV1ResponseError = (
  | authControllerRegisterCandidateV1Response401
  | authControllerRegisterCandidateV1Response409
) & {
  headers: Headers;
};

export type authControllerRegisterCandidateV1Response =
  | authControllerRegisterCandidateV1ResponseSuccess
  | authControllerRegisterCandidateV1ResponseError;

export const getAuthControllerRegisterCandidateV1Url = () => {
  return `/api/v1/auth/register-candidate`;
};

export const authControllerRegisterCandidateV1 = async (
  initCandidateProfileDto: InitCandidateProfileDto,
  options?: RequestInit,
): Promise<authControllerRegisterCandidateV1Response> => {
  return fetcher<authControllerRegisterCandidateV1Response>(
    getAuthControllerRegisterCandidateV1Url(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(initCandidateProfileDto),
    },
  );
};

export const getAuthControllerRegisterCandidateV1MutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerRegisterCandidateV1>>,
    TError,
    { data: InitCandidateProfileDto },
    TContext
  >;
  request?: SecondParameter<typeof fetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerRegisterCandidateV1>>,
  TError,
  { data: InitCandidateProfileDto },
  TContext
> => {
  const mutationKey = ["authControllerRegisterCandidateV1"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerRegisterCandidateV1>>,
    { data: InitCandidateProfileDto }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerRegisterCandidateV1(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerRegisterCandidateV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerRegisterCandidateV1>>
>;
export type AuthControllerRegisterCandidateV1MutationBody =
  InitCandidateProfileDto;
export type AuthControllerRegisterCandidateV1MutationError = void;

/**
 * @summary Initialize a candidate profile after Supabase signUp
 */
export const useAuthControllerRegisterCandidateV1 = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerRegisterCandidateV1>>,
      TError,
      { data: InitCandidateProfileDto },
      TContext
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerRegisterCandidateV1>>,
  TError,
  { data: InitCandidateProfileDto },
  TContext
> => {
  return useMutation(
    getAuthControllerRegisterCandidateV1MutationOptions(options),
    queryClient,
  );
};

/**
 * Frontend calls this AFTER supabase.auth.signUp() succeeds. Creates profiles + recruiter_profiles + companies rows in a single transaction.
 * @summary Initialize a recruiter profile + company after Supabase signUp
 */
export type authControllerRegisterRecruiterV1Response201 = {
  data: ProfileResponseEnvelopeDto;
  status: 201;
};

export type authControllerRegisterRecruiterV1Response401 = {
  data: void;
  status: 401;
};

export type authControllerRegisterRecruiterV1Response409 = {
  data: void;
  status: 409;
};

export type authControllerRegisterRecruiterV1ResponseSuccess =
  authControllerRegisterRecruiterV1Response201 & {
    headers: Headers;
  };
export type authControllerRegisterRecruiterV1ResponseError = (
  | authControllerRegisterRecruiterV1Response401
  | authControllerRegisterRecruiterV1Response409
) & {
  headers: Headers;
};

export type authControllerRegisterRecruiterV1Response =
  | authControllerRegisterRecruiterV1ResponseSuccess
  | authControllerRegisterRecruiterV1ResponseError;

export const getAuthControllerRegisterRecruiterV1Url = () => {
  return `/api/v1/auth/register-recruiter`;
};

export const authControllerRegisterRecruiterV1 = async (
  initRecruiterProfileDto: InitRecruiterProfileDto,
  options?: RequestInit,
): Promise<authControllerRegisterRecruiterV1Response> => {
  return fetcher<authControllerRegisterRecruiterV1Response>(
    getAuthControllerRegisterRecruiterV1Url(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(initRecruiterProfileDto),
    },
  );
};

export const getAuthControllerRegisterRecruiterV1MutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerRegisterRecruiterV1>>,
    TError,
    { data: InitRecruiterProfileDto },
    TContext
  >;
  request?: SecondParameter<typeof fetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerRegisterRecruiterV1>>,
  TError,
  { data: InitRecruiterProfileDto },
  TContext
> => {
  const mutationKey = ["authControllerRegisterRecruiterV1"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerRegisterRecruiterV1>>,
    { data: InitRecruiterProfileDto }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerRegisterRecruiterV1(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerRegisterRecruiterV1MutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerRegisterRecruiterV1>>
>;
export type AuthControllerRegisterRecruiterV1MutationBody =
  InitRecruiterProfileDto;
export type AuthControllerRegisterRecruiterV1MutationError = void;

/**
 * @summary Initialize a recruiter profile + company after Supabase signUp
 */
export const useAuthControllerRegisterRecruiterV1 = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerRegisterRecruiterV1>>,
      TError,
      { data: InitRecruiterProfileDto },
      TContext
    >;
    request?: SecondParameter<typeof fetcher>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerRegisterRecruiterV1>>,
  TError,
  { data: InitRecruiterProfileDto },
  TContext
> => {
  return useMutation(
    getAuthControllerRegisterRecruiterV1MutationOptions(options),
    queryClient,
  );
};
