/**
 * Static taxonomy used by the Skills typeahead in the candidate onboarding Review step.
 * Sorted alphabetically for stable diffs. Expand over time as real candidate data flows in.
 */
export const SKILLS_TAXONOMY: readonly string[] = [
  ".NET",
  "AWS",
  "Adobe XD",
  "Agile",
  "Algorithms",
  "Android",
  "Angular",
  "Ansible",
  "Apache Kafka",
  "Apache Spark",
  "Azure",
  "Bash",
  "BigQuery",
  "C",
  "C#",
  "C++",
  "CI/CD",
  "CSS",
  "Cassandra",
  "Celery",
  "Clojure",
  "Cloud Run",
  "CloudFormation",
  "Cypress",
  "DDD",
  "Django",
  "Docker",
  "DocumentDB",
  "DynamoDB",
  "ElasticSearch",
  "Elixir",
  "Ember.js",
  "Express",
  "FastAPI",
  "Figma",
  "Flask",
  "Flutter",
  "GCP",
  "Git",
  "GitHub Actions",
  "GitLab CI",
  "Go",
  "GraphQL",
  "Gradle",
  "Hadoop",
  "Haskell",
  "Heroku",
  "HTML",
  "Helm",
  "Java",
  "JavaScript",
  "Jenkins",
  "Jest",
  "Kafka",
  "Keras",
  "Kotlin",
  "Kubernetes",
  "LangChain",
  "Linux",
  "Lua",
  "Machine Learning",
  "MariaDB",
  "Maven",
  "Microservices",
  "MongoDB",
  "MySQL",
  "NestJS",
  "Next.js",
  "Node.js",
  "Nuxt.js",
  "OAuth",
  "OpenAI API",
  "OpenAPI",
  "OpenTelemetry",
  "PHP",
  "Perl",
  "Playwright",
  "PostgreSQL",
  "Postman",
  "PowerShell",
  "Prisma",
  "Prometheus",
  "Pub/Sub",
  "Puppeteer",
  "PyTorch",
  "Python",
  "R",
  "REST APIs",
  "RabbitMQ",
  "Rails",
  "React",
  "React Native",
  "Redis",
  "Redux",
  "Ruby",
  "Rust",
  "SCSS",
  "SQL",
  "SQLite",
  "Sass",
  "Scala",
  "Selenium",
  "Sentry",
  "Shell scripting",
  "Snowflake",
  "Spark",
  "Spring Boot",
  "Storybook",
  "Stripe",
  "Supabase",
  "Svelte",
  "Swift",
  "System Design",
  "Tailwind CSS",
  "TanStack Query",
  "TensorFlow",
  "Terraform",
  "TypeScript",
  "Unity",
  "Vue.js",
  "Webpack",
  "WebSockets",
  "Zod",
];
