// Re-export canonical enums + types from @aurahire/db.
// Frontend code should import enums from @aurahire/shared, not @aurahire/db.

export {
  USER_ROLES,
  USER_STATUS,
  APPLICATION_STATUS,
  APPLICATION_SCORE_STATUS,
  OFFER_STATUS,
  INTERVIEW_FORMAT,
  INTERVIEW_STATUS,
  INTERVIEW_RECOMMENDATION,
  JOB_STATUS,
  EMPLOYMENT_TYPE,
  WORK_MODE,
  EXPERIENCE_LEVEL,
  EDUCATION_REQUIREMENT,
  COMPANY_SIZE,
  SCORE_BAND,
  SCORE_STATUS,
  RESUME_PARSE_STATUS,
  BIAS_CATEGORY,
  BIAS_FLAG_STATUS,
  BIAS_SEVERITY,
  AUDIT_ACTOR_TYPE,
  PARSE_CONFIDENCE,
  EVIDENCE_RELEVANCE,
  SCORE_TYPE,
  SCORE_COMPONENT_PROFILE,
  SCORE_COMPONENT_MATCH,
  COMPANY_MEMBER_ROLE,
  COMPANY_MEMBER_STATUS,
  FEEDBACK_TYPE,
  FEEDBACK_SEVERITY,
  FEEDBACK_STATUS,
} from "@aurahire/db";

export type {
  UserRole,
  UserStatus,
  ApplicationStatus,
  ApplicationScoreStatus,
  OfferStatus,
  InterviewFormat,
  InterviewStatus,
  InterviewRecommendation,
  JobStatus,
  EmploymentType,
  WorkMode,
  ExperienceLevel,
  EducationRequirement,
  CompanySize,
  ScoreBand,
  ScoreStatus,
  ResumeParseStatus,
  BiasCategory,
  BiasFlagStatus,
  BiasSeverity,
  AuditActorType,
  ParseConfidence,
  EvidenceRelevance,
  ScoreType,
  CompanyMemberRole,
  CompanyMemberStatus,
  FeedbackType,
  FeedbackSeverity,
  FeedbackStatus,
} from "@aurahire/db";
